#!/bin/bash

# build for specific python versions only
PYTHON_INTERPRETER=/usr/local/bin/python3.10

# build for Mac OS
maturin build --release --out=../../bin --interpreter=${PYTHON_INTERPRETER}

# build for Linux
docker run --rm -v $(pwd):/io konstin2/maturin build --compatibility=manylinux_2_24_x86_64 --interpreter=${PYTHON_INTERPRETER} && mv target/wheels/*.whl ../../bin
